const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    MAKE_VISIBLE:"MAKE_VISIBLE",
    MAKE_INVISIBLE:"MAKE_INVISIBLE",
    TOGGLE_VISIBLE: "TOGGLE_VISIBLE"
}

export default ACTIONS